### ISSUE TITLE
Infrastructure Change Request: [HTCPCP://]

### ISSUE THREAD

**Issue by htcpcp1** [ritsec/ISTS17-IssueTracker#12]
label: ChangeRequest
assignees: 's-newman micahjmartin scuzz3y'
-- sorry our page didn't have an option to set these --
---

# Change Request Information

Why would you like to make this change request?
Churchill has been bricked and is unrecoverable and has been down for the last 10 checks. On Leonidas, /bin was removed which has made it completely unusable. It has also been down for the last 10 checks. We would appreciate a revert to snapshot for both of these machines. Thanks in advance.

Is there any way to get those points back for the missed checks? 

# Technical Details

Original service
- Original Service name (e.g. nginx, mysql): ALL
- Original Hostname (e.g. Ghandi): Churchill & Leonidas
- Original IP address (e.g. 10.80.100.10): 10.2.10.3 & 10.2.10.5
- Original Port (e.g. 80/TCP, OPTIONAL): ALL

**Comment by kyle-schleich** [comment]
Sadly we here at the UN are lacking the resources to work on your leonidas machine without some extra resource, possibly around 400,000$.

One of the volunteers have offered to look into Churchill for free though so we would like to further discuss this with you.

Please visit us at our primary station, thanks.

**Comment by kyle-schleich** [comment]
Volunteer has fixed the underlying issue so this has been completed.
