### ISSUE TITLE
Infrastructure Change Request: Team6 

### ISSUE THREAD

**Issue by liamcs98** [ritsec/ISTS17-IssueTracker#13]
# Change Request Information

Why would you like to make this change request?
Hi Black team!

I am trying to get one of our machines reset as it has been corrupted since right before lunch.

# Technical Details

Original service:
The machine is:
Team 6 - Julius
10.2.6.2

Target service:
Revert to snapshot.

**Comment by poptar7** [comment]
Can confirm is bricked.

**Comment by poptar7** [comment]
This is the UN election monitoring commission, sadly we are currently strapped of funds. Thus we will only be able to help you in the most dire of circumstances, or maybe a donation of say 400,000$.

Thanks

**Comment by liamcs98** [comment]
Hi! After completing the Karaoke challenge we were to get the machine reverted.

**Comment by liamcs98** [comment]
And never mind! Closing this thread after in person interact.
