### ISSUE TITLE
Julius bricked

### ISSUE THREAD

**Issue by eiffel651** [ritsec/ISTS17-IssueTracker#14]
Our julius machine was bricked and they deleted our entire boot file
Team 9

**Comment by kyle-schleich** [comment]
Can confirm is a bricked boi

**Comment by kyle-schleich** [comment]
This is the UN election monitoring commission, sadly we are currently strapped of funds. Thus we will only be able to help you in the most dire of circumstances, or maybe a donation of say 400,000$.

Thanks
