### ISSUE TITLE
Infrastructure Change Request: [TEAM NAME]

### ISSUE THREAD

**Issue by hyttioaoa** [ritsec/ISTS17-IssueTracker#17]
# Change Request Information

To revert Alexander (Windows 2016 Server)

Why would you like to make this change request?
Red team can't connect and has no shells. We have been locked for the last few hours and need to reset the password for Jeff as it affects our ftp server and smtp server and those no longer work. 

# Technical Details
Net.exe binary has been tampered with, SystemNative has been renamed, password has been changed, netdom does not work. 

Original service
- Original Service name (e.g. nginx, mysql)
- Original Hostname (e.g. Ghandi)
- Original IP address (e.g. 10.80.100.10)
- Original Port (e.g. 80/TCP, OPTIONAL)

Target service
- New Service name (e.g. nginx, mysql)
- New Hostname (e.g. Washington)
- New IP address (e.g. 10.80.100.11)
- New Port (e.g. 8080/TCP, OPTIONAL)

**Comment by kyle-schleich** [comment]
This is the UN election monitoring commission, sadly we are currently strapped of funds. Thus we will only be able to help you in the most dire of circumstances, or maybe a donation of say 400,000$.

Thanks

**Comment by hyttioaoa** [comment]
@kyle-schleich I would argue this is pretty dire in regards to red team and us as they can't connect nor have fun. Furthermore, without the net binary and unable to use a usb it's rather complicated to change passwords :(

**Comment by kyle-schleich** [comment]
We have noticed the dire position your political party is currently in and believe that it is possible that other parties are attempting to influence this election.

In response to this we will be investing in the success of your party.

Yours truly UN electioneering division lead.

(For future reference please properly fill the form out.)
