### ISSUE TITLE
Infrastructure Change Request: [UBGEESE]

### ISSUE THREAD

**Issue by ubgeese** [ritsec/ISTS17-IssueTracker#19]
# Change Request Information

Why would you like to make this change request?
We would like to migrate service SMTP from XERXES to ALEXANDER.
# Technical Details
Due to problems with server "XERXES" we are requesting to change the existing SMTP service to Alexander from "XERXES".
Reasons:
- "XERXES" is outdated
- "XERXES" is not currently being able to boot

Original service
- Original Service name SMTP
- Original Hostname XERXES
- Original IP address 10.2.7.6
- Original Port 25

Target service
- New Service name  SMTP
- New Hostname Alexander
- New IP address 10.2.7.1
- New Port 25

**Comment by micahjmartin** [comment]
Approved
