### ISSUE TITLE
Infrastructure Change Request: [UBnetdef Helpdesk]

### ISSUE THREAD

**Issue by ubnetdefhelpdesk** [ritsec/ISTS17-IssueTracker#3]
# Change Request Information

Why would you like to make this change request?
Team 1 - our last machine (Xerxes) is down and needs a revert.
The boot manager is completely broken, no specific change in any one service.

# Technical Details

Original service
- Original Service name (e.g. nginx, mysql)
- Original Hostname (e.g. Ghandi): 
- Original IP address: 10.2.0.6
- Original Port (e.g. 80/TCP, OPTIONAL)

Target service
- New Service name (e.g. nginx, mysql)
- New Hostname (e.g. Washington)
- New IP address (e.g. 10.80.100.11)
- New Port (e.g. 8080/TCP, OPTIONAL)

**Comment by kyle-schleich** [comment]
You did this wrong.

Is this Ghandi or Xerces

**Comment by ubnetdefhelpdesk** [comment]
Xerxes

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kyle-schleich** [comment]
Please edit the original request with accurate information.

Thanks,
WhiteTeam HQ

**Comment by ubnetdefhelpdesk** [comment]
Why would you like to make this change request?
Team 1 - our last machine (Xerxes) is down and needs a revert.
The boot manager is completely broken, no specific change in any one service.
Error Message Status 0xc0000034
File \boot\bcd
The windows boot configuration data file is missing required information.
Original IP address: 10.2.0.6


# Technical Details
Original service

* Original Service name (e.g. nginx, mysql)
* Original Hostname (e.g. Ghandi):
* Original IP address: 10.2.0.6
* Original Port (e.g. 80/TCP, OPTIONAL)

Target service

* New Service name (e.g. nginx, mysql)
* New Hostname (e.g. Washington)
* New IP address (e.g. 10.80.100.11)
* New Port (e.g. 8080/TCP, OPTIONAL)

**Comment by kyle-schleich** [comment]
Thank you for the request, for future reference the name you see in vcenter is the hostname.

This will be addressed and closed when completed
