### ISSUE TITLE
Infrastructure Change Request: Hyttioaoa

### ISSUE THREAD

**Issue by hyttioaoa** [ritsec/ISTS17-IssueTracker#4]
# Change Request Information

Why would you like to make this change request?

# Technical Details

Xerxes is bricked and it says I need a disk
To reset it?

Original service
- Original Service name (e.g. nginx, mysql)
- Original Hostname (e.g. Ghandi)
- Original IP address (e.g. 10.80.100.10)
- Original Port (e.g. 80/TCP, OPTIONAL)

Target service
- New Service name (e.g. nginx, mysql)
- New Hostname (e.g. Washington)
- New IP address (e.g. 10.80.100.11)
- New Port (e.g. 8080/TCP, OPTIONAL)

**Comment by kyle-schleich** [comment]
Please fill out the form (at least the hostname)

Regardless this will be addressed and closed when fixed.
