### ISSUE TITLE
Infrastructure Change Request: [TEAM NAME]

### ISSUE THREAD

**Issue by ubnetdefhelpdesk** [ritsec/ISTS17-IssueTracker#5]
# Change Request Information

Why would you like to make this change request?
The whole machine is down, there is no prompt for me to login and I need to do the graylog inject.

# Technical Details

Original service
- Original Service name : Graylog
- Original Hostname : Leonidas
- Original IP address : 10.1.2.4

Target service
- New Service name: Graylog
- New Hostname: Leonidas
- New IP address: 10.1.2.4

**Comment by kyle-schleich** [comment]
Being looked into.

**Comment by kyle-schleich** [comment]
Reset done
