### ISSUE TITLE
Leonidas needs to be reset for The Gophers

### ISSUE THREAD

**Issue by thegophers** [ritsec/ISTS17-IssueTracker#7]
# Change Request Information

The Leonidas server has proven to be unreliable for our campaign usage. Like many other teams, this box has been bricked and needs to be reset. We've contacted our higher ups (white team) and were told to make an issue here to resolve it.

# Technical Details

Please revert the Leonidas screenshot at your earliest convenience, please. Thank you!

**Comment by thegophers** [comment]
This is the same problem as seen here: https://github.com/ritsec/ISTS17-IssueTracker/issues/6

**Comment by kyle-schleich** [comment]
Reset done.
