### ISSUE TITLE
Julius needs to be reset for The Gophers

### ISSUE THREAD

**Issue by thegophers** [ritsec/ISTS17-IssueTracker#8]
# Change Request Information

The Julius server has proven to be unreliable for our campaign usage. Like many other teams, this box has been bricked and needs to be reset. We've contacted our higher ups (white team) and were told to make an issue here to resolve it.

# Technical Details

Please revert the Julius screenshot at your earliest convenience, please. Thank you!

**Comment by kyle-schleich** [comment]
Being looked into.

**Comment by thegophers** [comment]
Thank you @kyle-schleich ❤️

**Comment by kyle-schleich** [comment]
This is the UN election monitoring commission, sadly we are currently strapped of funds. Thus we will only be able to help you in the most dire of circumstances, or maybe a donation of say 400,000$.

Thanks
